import random

EXTERIORS = {
    "material": [
        "Gray Brick",
        "Stone & Timbers",
        "Cut Stone and Blocks",
        "Wooden Boards",
        "Plaster Board & Timbers",
        "Metal Sheeting",
    ],
    "details": [
        "Tile Work",
        "Iron Work",
        "Glass Work",
        "Stone Work",
        "Wood Work",
        "Landscaping",
    ],
}
USE_COMMON = [
    "Bunk House",
    "Inn",
    "Tavern",
    "Gambling Hall",
    "Drug Den",
    "Brothel",
    "Market",
    "Workshop",
    "Bakery",
    "Butchery",
    "Forge",
    "Tailory",
    "Work House",
    "Goat Stables",
    "Brewery",
    "Watch Post",
    "Court, Jail",
    "Dock",
    "Ruin",
    "Row Houses",
    "Tenements",
    "Apartment Buildings",
    "Small House",
    "Bath House",
    "Shrine",
    "Tattooist",
    "Physicker",
    "Fighting Pits",
    "Square, Fountain",
    "Grotto",
    "Warehouse",
    "Stockyard",
    "Factory",
    "Refinery",
    "Eelery",
    "Mushroom Garden",
]
USE_RARE = [
    "Market House",
    "Restaurant",
    "Bar, Lounge",
    "Academy",
    "Salon",
    "Cafe",
    "Floristry",
    "Tobacconist",
    "Book Shop",
    "Jeweler",
    "Clothier",
    "Gallery",
    "Apothecary",
    "Horse Stables",
    "Distillery",
    "Vintner",
    "Master Artisan",
    "Boat House",
    "Theater",
    "Opera House",
    "Apartment Building",
    "Townhouse",
    "Manor House",
    "Villa",
    "Clinic",
    "Temple",
    "Cistern",
    "Watch Post",
    "Park",
    "Monument",
    "Archive",
    "Spiritualist",
    "Bank",
    "Alchemist",
    "Power Plant",
    "Radiant Energy Garden",
]
DETAILS = [
    "Dripping Water",
    "Creaking Floorboards",
    "Roaring Fires",
    "Smoky Lamps",
    "Buzzing Electric Lights",
    "Ticking Clockworks",
    "Plants, Flowers",
    "Wall Hangings, Artwork",
    "Shuttered Windows",
    "Heavy Curtains, Thick Carpet",
    "Dust, Detritus",
    "Wear, Damage",
    "Threadbare, Tattered",
    "Utilitarian Furnishings",
    "Elegant Finery",
    "Lush, Comfortable",
    "Rough-Spun Simplicity",
    "Spartan Austerity",
    "Circular Stairs",
    "Ladders",
    "Secret Doors",
    "Catwalks",
    "Skylights",
    "Balcony",
    "Cellar",
    "Drafty, Cold",
    "Stout, Quiet",
    "Cozy, Warm",
    "Vaulted, Spacious",
    "Low, Cramped",
    "Rickety, Ramshackle",
    "Strange Devices",
    "Weird Artifacts",
    "Spirit Wards, Old Runes",
    "Piled Jumble of Curios",
    "Antique Appointments",
    "Shrine, Altar",
]


class Building:
    def __init__(self, rarity):
        self.rarity = rarity
        self.exterior = {
            "material": random.choice(EXTERIORS["material"]),
            "details": random.choice(EXTERIORS["details"]),
        }
        if self.rarity == "common":
            self.use = random.choice(USE_COMMON)
        if self.rarity == "rare":
            self.use = random.choice(USE_RARE)
        self.details = random.choice(DETAILS)

    def __str__(self):
        return f"""A Building with {self.rarity} and {self.details}"""
